language: node_js
os: linux
dist: bionic
jobs:
  include:
    - name: Test on stable Node.js
      node_js: stable
    - name: Test on Node.js 12
      node_js: 12
    - name: Test on Node.js 10
      node_js: 10
    - name: Test on Node.js 8
      node_js: 8
    - name: Test on Node.js 6
      node_js: 6
    - name: Test on Node.js 4
      node_js: 4
