language: node_js
os: linux
dist: bionic
jobs:
  include:
    - name: Test on stable Node.js
      node_js: stable
    - name: Test on stable Node.js with React 15
      node_js: stable
      before_script: npm install --no-save react@15 react-dom@15
    # - name: Test on stable Node.js with React 0.14
    #   node_js: stable
    #   before_script: npm install --no-save react@0.14 react-dom@0.14
    - name: Test on Node.js 12
      node_js: 12
    - name: Test on Node.js 10
      node_js: 10
    - name: Test on Node.js 8
      node_js: 8
    - name: Test on Node.js 6
      node_js: 6
    - name: Test on Node.js 4
      node_js: 4
